### PR TITLE
Make folder dynamic. and adding persian translate

### PR DESCRIPTION
**Pull request by hooman-mirghasemi**
with this code if you want you can set dir in connectorRoute 
like:
'connectorRoute' => ['el-finder/connector' , 'dir'=>'doctor-'.$doctorModel->id],

so it make a folder for each doctor.

### CODE REVIEW

**Comment by zxbodya** [comment]
there is security issue with this addition - what if user pass `dir=../`?

**Comment by hooman-mirghasemi** [comment]
that's right . you can add a little code to fix it and remove ../ from connectorRoute array.
or if you want i do it and send as pull request?

**Comment by zxbodya** [comment]
I would prefer not exposing such possibility to client-side at all… 

For example in you case, I would suggest creation separate action for it, which will take `$doctorModel->id` as parameter, and after validating it will do logic you suggested to add to extension.

**Comment by hooman-mirghasemi** [comment]
That's not have different on do checking dir in other action or in ConnectorAction of ext only if checking in one other action it will be take more time!



public function run()
    {
        require_once(dirname(__FILE__) . '/php/elFinder.class.php');
        if(isset($_GET['dir'])){
            $dir = str_replace('..','',$_GET['dir']);
            $this->settings['URL'] = $this->settings['URL'].$dir.'/';
            $this->settings['root'] = $this->settings['root'].$dir.'/';
            if(!file_exists($this->settings['root'])){
                mkdir($this->settings['root'], 0777, true);
            }
        }
        $fm = new \elFinder($this->settings);
        $fm->run();
    }

**Comment by zxbodya** [comment]
no, it is different from doing check in separate action… while using `$_GET['dir']` you might access other folders you should not… I consider this to be possible security issue in many cases…

like in your case `$doctorModel->id ` - it is possible that your will need to limit access by this `id`, or if you want to check if model with specified id exists

**Comment by hooman-mirghasemi** [comment]
ok
Something else, it is better to add version for this ext in release : https://github.com/zxbodya/yii2-elfinder/releases there is not tag or release yet.
like 1.0.0

**Pull request closed without merging**
